name: AutoMerge Transifex Pull Requests
on: pull_request
  branches:
    - '!update-l10n'

jobs:
  approve:
    runs-on: ubuntu-latest
    name: Approve
    steps:
      - uses: hmarr/auto-approve-action@v2.2.1
        if: github.actor == 'transifex-integration[bot]'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

  automerge:
    runs-on: ubuntu-latest
    name: Auto-merge
    steps:
      - uses: pascalgn/automerge-action@v0.15.6
        if: github.actor == 'transifex-integration[bot]'
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""
          MERGE_RETRIES: 10
          MERGE_RETRY_SLEEP: 60000
