name: AutoMerge Transifex Pull Requests
on:
  pull_request:

permissions:
  contents: read

jobs:
  approve:
    if: github.event.pull_request.user.login == 'transifex-integration[bot]'
    runs-on: ubuntu-latest-low
    permissions:
      # for hmarr/auto-approve-action to approve PRs
      pull-requests: write
      # for alexwilson/enable-github-automerge-action to approve PRs
      contents: write

    name: Approve
    steps:
      - uses: hmarr/auto-approve-action@f0939ea97e9205ef24d872e76833fa908a770363 # v4.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      # Enable GitHub auto merge
      - name: Auto merge
        uses: alexwilson/enable-github-automerge-action@56e3117d1ae1540309dc8f7a9f2825bc3c5f06ff # v2.0.0
        if: startsWith(steps.branchname.outputs.branch, 'translations_')
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
